[project]
name = "udemy-scraper"
version = "0.1.0"
description = "Scrapes data from my courses"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.12",
    "boto3>=1.35",
    "pytesseract>=0.3.13",
    "requests>=2.32",
]
